### PR TITLE
audio(koala): add new audio filter KoalaFilter

### PR DESCRIPTION
**Pull request by aconchillo**
#### Please describe the changes in your PR. If it is addressing an issue, please reference that as well.

Adds a new audio filter for noise reduction using Koala Noise Suppression. 

https://picovoice.ai/platform/koala/

### CODE REVIEW

**Comment by markbackman** [comment]
Very cool! Can you add a simple foundational example showing how to use this? Or, we can opt to not do that and just update the docs for this. WDYT?

Either way, it looks good! I tested it locally.

**Review by markbackman — APPROVED** [review]
Approving to not block this. I'll add a docs page.

**Comment by markbackman** [comment]
Docs PR showing how to use it: https://github.com/pipecat-ai/docs/pull/67.

**Comment by aconchillo** [comment]
> Very cool! Can you add a simple foundational example showing how to use this? Or, we can opt to not do that and just update the docs for this. WDYT?
> 
> Either way, it looks good! I tested it locally.

I think we don't need another example, since it's just one line change from the Krisp one. Thanks for the docs update!

**Pull request merged**
