### PR TITLE
services(together): fix together AI InputParams

### PR DESCRIPTION
**Pull request by aconchillo**

### CODE REVIEW

**Comment by aconchillo** [comment]
@kwindla Looking at the together service I realized we earlier rejected a PR that was adding Groq. At the end they are both very similar. I'm wondering if we should reconsider that.

**Comment by aconchillo** [comment]
This is the PR we closed: https://github.com/pipecat-ai/pipecat/pull/419

**Review by markbackman — APPROVED** [review]
LGTM.

I'm wondering if it makes sense to keep around Together as a processor since it's been hollowed out so much. At this point, it's just using the base_url from OpenAILLMService. (Though, it serves as a good example.)

**Comment by aconchillo** [comment]
Yes, I meant adding the `Groq` one.

**Pull request merged**
