### PR TITLE
rtvi: add RTVIUserLLMTextProcessor

### PR DESCRIPTION
**Pull request by aconchillo**

### CODE REVIEW

**Comment by kwindla** [comment]
My quick take is that we need this pipeline element, but that we also have a message ordering bug that we should fix. I think that the last "final" transcription message gets delayed behind the first few messages from later elements in the pipeline. @marcus-daily mentioned this on Friday, too.

**Comment by markbackman** [comment]
I dropped @aconchillo a note on this too. I was seeing that transcript messages were getting dropped, resulting in, at times, only the last `final` transcript message appear. I traced this early today and found that the interruption handling logic deletes messages from the queue when an interruption occurs—this includes the transcription messages. So, the fix is to add a new frame type, @aconchillo was thinking of calling it `TransportSystemFrame`, which is not queued. This will eliminate the deleted transcripts problem and likely make this change for `RTVIUserLLMTextProcessor` unnecessary.

**Comment by aconchillo** [comment]
I just added `TransportMessageUrgentFrame`. We already have an `urgent` in `TransportMessageFrame`, but that didn't prevent the frame to be dropped (because it's just a field). The `urgent` was used at the output transport to send it right away or queue it internally. So, I have removed `urgent` (which actually was only used by RTVI) and created the `TransportMessageUrgentFrame`. I haven't had time to test it though yet.

**Comment by aconchillo** [comment]
I think  `RTVIUserLLMText` is still be needed and it's probably more accurate than transcription because the user aggregator can add 2 sentences for example (right now it's just one, but who knows).

That is:
- `user-transcription` is whatever the STT gives us.
- `user-llm-text` is whatever we aggregated from the user. and provide to the LLM.

**Review by markbackman — APPROVED** [review]
LGTM

**Pull request merged**
