### PR TITLE
Add conversation flow management (Pipecat Flows!)

### PR DESCRIPTION
**Pull request by markbackman**
#### Please describe the changes in your PR. If it is addressing an issue, please reference that as well.

This PR introduces a node-based conversation management system to Pipecat, making it easier for developers to create structured, multi-turn conversations with clear state transitions.

At its core, this system treats conversations as a series of connected nodes, where each node represents a distinct state in the conversation. Think of it like a choose-your-own-adventure book, where each page (node) presents specific options (functions) that determine where the story goes next.

## How nodes work

Each node contains:
- Messages that set the context for the LLM
- Available functions that can be called at this point
- Optional actions that execute when entering or leaving the node

Functions in a node can work in two ways:
1. **Transitional Functions**: These move you to a new node. For example, choosing between pizza or sushi moves you from the start node to either the pizza or sushi node.
2. **Terminal Functions**: These execute but keep you in the same node. For example, in a pizza ordering node, selecting a size is a terminal function—you stay in the pizza node because you might want to change the size. Terminal functions may also be used to end the call.

## Example

Consider a food ordering system:
1. The conversation starts in a "start" node where the user chooses their food type
2. Based on their choice, we transition to a specific ordering node
3. Within each ordering node, the user can:
   - Make selections (terminal functions)
   - Change their mind (terminal functions)
   - Complete their order (transition to end node)

The system handles these transitions while maintaining appropriate context and available options at each step.

## New classes

The implementation consists of two main classes:
- `FlowState`: Handles the state machine logic
- `FlowManager`: Coordinates between the state machine and Pipecat's pipeline

### CODE REVIEW

**Comment by Allenmylath** [comment]
wow is this gonna get capabilities like langgraph?

**Comment by markbackman** [comment]
> wow is this gonna get capabilities like langgraph?

This has similar concepts to langgraph, but is tailored for Pipecat. We'll have more to say about our goals shortly!

**Comment by markbackman** [comment]
Pipecat Flows is now a separate python package. You can check it out at: https://github.com/pipecat-ai/pipecat-flows.

This PR is now an update to pyproject.toml and adds an foundational example: `25-conversation-flow.py`

**Review by kwindla — APPROVED** [review]
lgtm

**Pull request merged**
