### PR TITLE
introduce audio filters

### PR DESCRIPTION
**Pull request by aconchillo**

### CODE REVIEW

**Review by markbackman — APPROVED** [review]
Very nice! 👏

**Comment by aconchillo** [comment]
@markbackman I have moved the `SilerVAD` processor to `processors.audio.vad`. So in `audio` we just have low-level stuff.

**Comment by markbackman** [comment]
Change looks good to me. I'm not too familiar with the VAD but the splitting into low level and processor makes a lot of sense.

**Comment by aconchillo** [comment]
> The change looks good to me. I'm not too familiar with the VAD but the splitting into low level and processor makes a lot of sense.

Moved the VAD part into a separate PR https://github.com/pipecat-ai/pipecat/pull/619. I still want to experiment with the audio filters.

**Pull request merged**
