### PR TITLE
Groq Support

### PR DESCRIPTION
**Pull request by keenborder786**
I have added Groq Support as an LLM Service

### CODE REVIEW

**Comment by manish-baghel** [comment]
@keenborder786 
Any reason for not using groq's official python client?

ref: https://console.groq.com/docs/libraries

**Comment by joachimchauvet** [comment]
This was already discussed in #419

Imho, I would lean toward using the official Groq python client should we start adding dedicated services.
You can always use the existing OpenAILLMService with the Groq API:
```python
llm = OpenAILLMService(
    name="LLM", api_key=GROQ_API_KEY, model=model_name, base_url="https://api.groq.com/openai/v1"
)
```

**Comment by keenborder786** [comment]
> This was already discussed in #419
> 
> Imho, I would lean toward using the official Groq python client should we start adding dedicated services. You can always use the existing OpenAILLMService with the Groq API:
> 
> ```python
> llm = OpenAILLMService(
>     name="LLM", api_key=GROQ_API_KEY, model=model_name, base_url="https://api.groq.com/openai/v1"
> )
> ```

Okay but I thought since we have `Together.AI` in similar way, it might be better to add Groq Processor in similar way otherwise people usually get confused if Groq is supported by Pipecat.

**Comment by markbackman** [comment]
After some back and forth, we've decided to adopt the pattern of using a service adapter, where the LLM service uses the OpenAILLMService base class to create the new LLM class. Then in that new LLM class, we can add service specific changes. We've made this change for:
- Azure
- Fireworks
- Together

And, we've added:
- Grok
- Groq

Thanks for the PR and for continuing to push for this idea.

Here's the PR where all of that is implemented: https://github.com/pipecat-ai/pipecat/pull/775.

Closing this PR.

**Pull request closed without merging**
