### PR TITLE
Updated the import package

### PR DESCRIPTION
**Pull request by sahilsuman933**

### CODE REVIEW

**Comment by markbackman** [comment]
Thanks for catching this @sahilsuman933. Do you mind updating the other instances of `CartesiaHttpTTSService` to use `CartesiaTTSService`?

**Comment by markbackman** [comment]
Thanks!

**Comment by markbackman** [comment]
@sahilsuman933 there's a conflict. Once you resolve that, I can merge this down.

**Comment by aconchillo** [comment]
Unfortunately we can't do this. There's a reason why we use the HTTP version in these examples. The HTTP version blocks until the audio frames are pushed. In the next Pipecat version we will try to figure out how to make `CartesiaTTSService` work with these examples as well. But for now we have to leave it like it is.

**Pull request closed without merging**
