### PR TITLE
Add three foundational examples for Pipecat Flows

### PR DESCRIPTION
**Pull request by markbackman**
#### Please describe the changes in your PR. If it is addressing an issue, please reference that as well.

Foundational examples:
- `25a-flow-food-ordering.py`
- `25b-flow-movie-booking.py`
- `25c-flow-travel-planner.py`

### CODE REVIEW

**Comment by aconchillo** [comment]
Shouldn’t we have these examples in Pipecat Flows itsefl?

**Comment by markbackman** [comment]
> Shouldn’t we have these examples in Pipecat Flows itself?

I do have JSON examples there: https://github.com/pipecat-ai/pipecat-flows/tree/main/editor/examples. I was included these examples as runnable versions of the JSON, since you can't run things with Pipecat Flows alone. WDYT?

**Comment by aconchillo** [comment]
> > Shouldn’t we have these examples in Pipecat Flows itself?
> 
> I do have JSON examples there: https://github.com/pipecat-ai/pipecat-flows/tree/main/editor/examples. I was included these examples as runnable versions of the JSON, since you can't run things with Pipecat Flows alone. WDYT?

Why not? Pipecat Flows should have `pipecat-ai` as a dependency. So you should be able to download Pipecat Flows and run the examples from there, like a completely independent project that depends on Pipecat.

**Comment by markbackman** [comment]
Closing in favor of #749.

**Pull request closed without merging**
