### PR TITLE
Gemini Multimodal Live API service

### PR DESCRIPTION
**Pull request by kwindla**
Support for Gemini 2.0 Multimodal Live API

### CODE REVIEW

**Comment by markbackman** [comment]
Want to rename the demos:
- 26 / 26a / 26b

OR

- 26a / 26b / 26c

**Review by markbackman — APPROVED** [review]
I made a few tiny fixes, but this looks great! 🔥

**Comment by nileshtrivedi** [comment]
Beginner here, but why do all Gemini Multimodal examples require Daily's WebRTC transport? Gemini offers a direct realtime API, isn't it? Is there an example that only relies on Gemini services?

**Comment by markbackman** [comment]
@nileshtrivedi you can connect directly to Gemini Multimodal either through Gemini's API or through a transport built by the Pipecat team: https://github.com/pipecat-ai/pipecat-client-web-transports/tree/main/transports/gemini-live-websocket-transport.

The biggest downside is that the direct connection to Gemini is via Websocket, which isn't suitable for client/server production use. You can read a short primer on this here: https://www.daily.co/videosaurus/websockets-and-webrtc/.

Also, Pipecat is about orchestration. If you need more than just a direct connection (e.g. you need to manage an LLM context, set tools, collect metric, etc), you'll need a framework like Pipecat. Gemini is only a model + websocket transport.

**Pull request merged**
