### PR TITLE
Deepgram Connection Issue if user speaks early

### PR DESCRIPTION
**Pull request by keenborder786**
Solve the following issue #427

### CODE REVIEW

**Comment by pushpak1300** [comment]
I tested this on this branch. Looks good 👍🏻👍🏻

**Comment by sardar1592** [comment]
Simple but good solution

**Comment by aconchillo** [comment]
Thank you! While the fix seems to solve the issue, I believe the problem is a bit deeper. If you can reproduce again (without this patch). Do you mind pasting TRACE logs of the bot's output? I'd like to confirm my hypothesis (basically that an audio frame is sent before the `StartFrame`).

**Comment by aconchillo** [comment]
I believe this PR should fix this issue (need to try it more) https://github.com/pipecat-ai/pipecat/pull/433

**Comment by aconchillo** [comment]
Verified #433 works. Thank you for sending this PR anyways!

If you have the time, I'd really appreciate if you could try it and see if it also fixes the issue for you. :pray:

**Comment by keenborder786** [comment]
@aconchillo sure

**Pull request closed without merging**
